### PR TITLE
asm: allow ";" to start a comment

### PR DESCRIPTION
**Pull request by SvOlli**
I'm having a big problem with "\" starting a comment. Every 6502 assembler I've worked with so far was using ";" for this. So I added this feature to "asm.com" as well.

### CODE REVIEW

**Comment by davidgiven** [comment]
That conflicts with the statement separator --- look at line 379.

I picked `\` because it's very slightly standard (used on the BBC Micro assembler), but I still hate it. I don't think anybody is using the statement separator yet, so it's probably possible to change. `.` or `:`, maybe?

**Comment by SvOlli** [comment]
Ah, I see what you mean. However, then using the colon ":" as the separator imho makes more sense, since I've seen that one in 6502 assemblers before. Those might have taken this over from BASIC.

**Comment by ivop** [comment]
Recently I read large parts of the cassette version of Elite for the BBC and noticed the ```\``` used for comments and figured that's where you got it from. Never encountered it before your cpm65 asm, but you get used to it quickly.

**Comment by SvOlli** [comment]
> ... but you get used to it quickly.

Nope. I've been working on CP/M stuff for weeks now. Seeing a single backslash still triggers my mind on "continue on next line" what it means almost everywhere else. (Like shell, Makefile, etc.)

However, I pushed a change here, changing the instruction separator from ";" to ":".

**Comment by SvOlli** [comment]
Browsing again through the code, I figured out my change of the code separators is incomplete, because I was not taking into account where the data stream gets modified into a separator. Working on it.

**Comment by davidgiven** [comment]
Sorry for the delay --- yes, that looks good.

**Comment by davidgiven** [comment]
No, it doesn't! `:` conflicts with label definitions, and there was a fair amount of other things internally which assumed ';' was the statement separator.

**Comment by SvOlli** [comment]
Yes. The completion of this is on my todo list. Other things got in the way.

**Comment by SvOlli** [comment]
So, I've updated the code with some non-functional changes. Mainly it's about replacing the tokens for instruction separator and comment. So if I figured out everything correctly, a switch should be rather easy, just change the defines, add the "old-style" comment and everything should be good.

About the colon ending a label: I was under the assumption, that this colon was read in a "tight loop", so it doesn't interfere with the others. Or do you mean that a missing colon in the label might trigger a problem with the internal structure where then a "separator-colon" is read as a "labelend-colon"?

**Comment by SvOlli** [comment]
Only slightly off-topic: the README.md states "The build system supports cc65 assembler and llvm-mos C programs." Is this correct? If so, is there an example?

**Pull request merged**
