### PR TITLE
Updated Atari port to new BDOS loader

### PR DESCRIPTION
**Pull request by ivop**
Hi,

I deleted my bdos loader and updated to your new loader.

Reserved tracks went from 3 to 1. Boot block size increased to 12 sectors instead of 10 with my limited loader. Can't have it all I suppose ;)

### CODE REVIEW

**Comment by ivop** [comment]
It's now in the same state as when my attempt at a BDOS loader. You can merge now, if you want to.

**Comment by ivop** [comment]
Sorry, there was a leftover of trying to move initdrivers to the loader segment, too. It's now in a mergeable state again.

**Comment by ivop** [comment]
Implemented proper tty_const. I was initially confused by the comment in the vic20 source (which turns out to be wrong) and had forgotten to go back to this. ^S and ^C now work during type bedit.asm.

Did not create a new branch/pull for this. You can still merge, if you want to.

**Comment by davidgiven** [comment]
Merged --- thanks!

**Pull request merged**
